###admin login

###read all users and authors
GET http://localhost:5000/admin-api/articles

###
GET http://localhost:5000/admin-api/users

###block or activate user or author
PATCH http://localhost:5000/admin-api/user/69b38ff5aaa5f2d4d18d0dc9
Content-Type: application/json

{
    "isUserActive":"true"
}
